auth:
  strategy: anonymous

external_services:
  istio:
    root_namespace: istio-system
  prometheus:
#    url: http://10.0.0.5:9091
    url: https://victoria-metrics.trial.studio
  grafana:
    enabled: false
    external_url: 'http://my-ingress-host/grafana'
    # Grafana datasource UID when there are multiple
    datasource_uid: ""
    dashboards:
      - name: "Istio Service Dashboard"
        variables:
          datasource: "var-datasource"
          namespace: "var-namespace"
          service: "var-service"
      - name: "Istio Workload Dashboard"
        variables:
          datasource: "var-datasource"
          namespace: "var-namespace"
          workload: "var-workload"
      - name: "Istio Mesh Dashboard"
      - name: "Istio Control Plane Dashboard"
      - name: "Istio Performance Dashboard"
      - name: "Istio Wasm Extension Dashboard"