role: Agent

customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 0.0.0.0:8686
  sources:
    kubernetes:
      type: kubernetes_logs
      namespace_annotation_fields:
        namespace_labels: ""
      node_annotation_fields:
        node_labels: ""
      pod_annotation_fields:
        pod_annotations: ""
        pod_ip: ""
        pod_ips: ""
        pod_labels: ""
        pod_namespace: ""
        pod_node_name: ""
        pod_owner: ""
        pod_uid: ""
        container_id: ""
        container_image_id: ""
  transforms:
    parser:
      type: remap
      inputs: [kubernetes]
      source: |
        .log = parse_json(.message) ?? .message
        del(.message)
  sinks:
    elasticsearch:
      type: elasticsearch
      inputs: [ parser ]
      endpoints: [ https://victoria-logs.trial.studio/insert/elasticsearch/ ]
      mode: bulk
      api_version: v8
      compression: zstd
      healthcheck:
        enabled: false
      request:
        headers:
          VL-Time-Field: timestamp
          VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name
          VL-Msg-Field: message,msg,_msg,log.msg,log.message,log
          AccountID: "0"
          ProjectID: "0"