apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name victoria-metrics-agent
spec:
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: *name
      targetRevision: 0.25.10
      helm:
        valueFiles:
          - $values/helm-values/victoria-metrics-agent/values.yaml
    - repoURL: https://github.com/ifbreadgood/kubernetes-base
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: *name
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
