apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name kube-state-metrics
spec:
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: *name
      targetRevision: 6.3.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: *name
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
