apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name argo-cd
  namespace: *name
spec:
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: *name
      targetRevision: 8.5.3
      helm:
        valueFiles:
          - $values/helm-values/argo-cd/values.yaml
    - repoURL: https://github.com/ifbreadgood/kubernetes-base
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ifbreadgood/kubernetes-base
      targetRevision: HEAD
      path: manifests/argo-cd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: *name
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
