apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name vector
spec:
  sources:
    - repoURL: https://helm.vector.dev
      chart: *name
      targetRevision: 0.46.0
      helm:
        valueFiles:
          - $values/helm-values/vector/values.yaml
    - repoURL: https://github.com/ifbreadgood/kubernetes-base
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: *name
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
