apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-argo-cd
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "https://vault.trial.studio"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "argo-cd"
          serviceAccountRef:
            name: "vault-argo-cd"
            audiences:
              - "external-secrets-operator"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc
spec:
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: oidc
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - remoteRef:
        key: argo-cd/oidc
        property: issuer
      secretKey: issuer
    - remoteRef:
        key: argo-cd/oidc
        property: client-id
      secretKey: client-id
