apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-custom:view-crds
rules:
  - verbs:
      - list
      - watch
    apiGroups:
      - apiextensions.k8s.io/v1
    resources:
      - customresourcedefinitions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-custom:reports-controller:view-crds
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: kyverno-custom:view-crds
subjects:
  - kind: ServiceAccount
    name: kyverno-reports-controller
    namespace: kyverno